capstone projects
Bantealem/Capstone-1 pull request #1
Opened 2022-07-29 08:09 UTC by Bantealem

It is my first capstone project

2022-07-29 09:45 UTC, ishimwezachee requested changes

2022-07-29 09:45 UTC, ishimwezachee commented on index.html
> +                    <div id="get-dishes" class="row"></div>
- [ ] You should have section for featured speakers as it is provided from the design. I know that your topic is not the same from behance design, but as you've chosen it you have to make sure that it contain all parts that behance design has as well. 
Make sure that it contain image, title, subtitle and description 
![image](https://user-images.githubusercontent.com/43877689/181727018-117f3046-2ea4-443f-8633-947c01289e63.png)

2022-07-29 09:45 UTC, ishimwezachee commented on index.html
> +                        class="col-lg-2 pt-5 pb-5 pt-lg-0 pb-lg-0 pe-4 col-md-4 col-4 px-0 justify-content-center d-flex align-item-center">
- [ ]  You should fix small postioning errors , and also try your best to using similar color and fonts to provided behance design 
![image](https://user-images.githubusercontent.com/43877689/181727569-fd74e24f-55ef-4016-aeac-67217fc7097d.png)

2022-07-29 09:45 UTC, ishimwezachee commented on about.html
> +      </p>
- [ ]  Your about page should be structured similar to the one from Behance design.  Make sure that your texts are colored, and their fonts and borders are similar to the ones from Behance design. 
Your design 
![image](https://user-images.githubusercontent.com/43877689/181728296-da3f52b8-030b-4965-a038-647d5301a57a.png)

Behance design 

![image](https://user-images.githubusercontent.com/43877689/181728501-25b7a5bd-5b57-4064-b45d-119d23294f9c.png)

2022-07-29 09:45 UTC, ishimwezachee commented on about.html
> +      Traditional Ethiopian Restaurant is nice place in Addis Ababa to enjoy great Ethiopian Food with LIVE dance show in
- [ ]   Your should position your elements similar to the one from Behance design, fix those small disorganised elements so that you can have well looking project 
![image](https://user-images.githubusercontent.com/43877689/181729358-b024d8c5-93e2-4acb-989e-f91cff8355e0.png)

2022-07-29 09:45 UTC, ishimwezachee commented on about.html
> +                </span>
- [ ]  Your images should have same blur background color similar to the one provided from Behance design 

Your design 
![image](https://user-images.githubusercontent.com/43877689/181729737-5a64dc69-4df0-4bb9-8d8f-2d1f80879eb1.png)

Behance design 

![image](https://user-images.githubusercontent.com/43877689/181729862-65f5d00a-70d1-48ce-9e33-630e559e7104.png)

2022-07-29 09:45 UTC, ishimwezachee commented on index.html
> +                    <img src="images/logo.png" class="logo-img" alt="logo" />
- [ ]  Fix your humburg menu button, after click on one navigation, it stoped working. make sure in mobile device mode, it present and working properly. especially after clicking home nav
![image](https://user-images.githubusercontent.com/43877689/181730562-515329ea-86fb-4dea-9c15-16a4fef98c0c.png)

2022-07-29 09:45 UTC, ishimwezachee commented on index.html
> +                                </h5>
- [ ]  You should have cards that has structure similar to the Behance design. Please try your best to have elements similar to the provided design 

Your design 
![image](https://user-images.githubusercontent.com/43877689/181731074-643b8708-eb67-4aaf-a61c-8bab8fbe9e5f.png)

Behance design 
![image](https://user-images.githubusercontent.com/43877689/181731146-f4a2299b-f300-4ded-9e82-d4c1b309519b.png)

2022-07-29 09:45 UTC, ishimwezachee commented on index.html
> +                    <div class="row mt-3 d-md-none d-lg-none d-xl-none">
- [ ] You should make your icnons in partner's section responsive. 

![image](https://user-images.githubusercontent.com/43877689/181731549-6dd8b28f-4d46-4852-9b35-1d319a4fd37d.png)

2022-07-29 09:45 UTC, ishimwezachee commented on about.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymou
- [ ]  Your about footer should have partner's section and footer itself. Please add it correctly, and arrange it in right way .

Your design 
![image](https://user-images.githubusercontent.com/43877689/181732095-0766478b-00c4-49df-b3be-1527f36d6375.png)

Behance design 

![image](https://user-images.githubusercontent.com/43877689/181732233-2219462d-c181-4743-9452-93f471751c36.png)

2022-07-30 07:31 UTC, vickymarz requested changes
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that has some failing linter checks. Kindly fix your linter error and submit again 👍 .

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-30 11:01 UTC, Danieldotcomcoder requested changes
Hello @Bantealem , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Made a lot of great changes 👍 👍 
- No Linter Errors 👍 👍  

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-30 18:02 UTC, medaminedev66 requested changes
Hi @Bantealem, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has some failing linter checks. Kindly fix your linter error and request another PR review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-30 18:48 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️ 
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

@Bantealem  ✋🏼 
#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
___ 

### 💯  Highlights 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
___

### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 

- Your commit messages should always start with capital letters and they should be an imperative tense. I see some of them are not like that. Instead of writing `Added style or Created the file` you should write `Add style or Create the file`
- ***I write it as optional. But this is a [general requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=The%20commit%20message%20should%20be%20written%20in%20the%20imperative%20tense%20and%20capitalized) for every project. So you should pay attention to this in your next projects.***
- You can change them by using `git-rebase`. If you want to know how to change ı leave a few resources.
- [Video - How to change commit messages](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6)
- [Article - How to create good commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-07-30 18:48 UTC, ahmetbozaci commented on index.html
> +        </section>
Like the last code reviewer said;
- [ ] Well done adding the speaker section. But it doesn't look the same as the original content can be different but the layout and colors should be the same. 
- [ ] Kindly add the title of the section
- [ ] Kindly delete the gray background of the section.
- [ ] Kindly add more text like the original design.
- [ ] Kindly delete the orange line left in the middle of the section.
- [ ] I can't see this section in the mobile version kindly fix it.
![image](https://user-images.githubusercontent.com/38635158/181937134-3bb6393b-176e-412a-8202-78ab6fc1bea9.png)
![image](https://user-images.githubusercontent.com/38635158/181937230-0c6d25a1-ce6f-4485-b5a8-6f2b674ad52b.png)

ORIGINAL
![image](https://user-images.githubusercontent.com/38635158/181937168-0563fdb3-7595-4c70-8cb0-39074cdbd68e.png)

2022-07-30 21:15 UTC, alexander16108 requested changes
Hi @Bantealem , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media3.giphy.com/media/0bfUJGAlN5HQhFZkWR/giphy.gif" style ="height:50px"/>

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-30 21:15 UTC, alexander16108 commented on index.html
> +            </div>
as per the project requirements: you are required to have six individual articles. each with an image, title, and subtitle. and description, please fix this and try again.

your design ⬇️ 
![image](https://user-images.githubusercontent.com/60612329/181996256-5e461660-033f-417d-ace9-8d39e6845346.png)

vs 

the required design
![image](https://user-images.githubusercontent.com/60612329/181996388-945417f4-b3ae-4d8d-880c-7e16b53ffa7e.png)

2022-08-01 13:42 UTC, sja-thedude approved these changes
## Project Approved 👍 

Hi @Bantealem, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Optional: Kindly fix your deployment it's failing. As it was not required by the previous reviewer that's the reason it's an optional. But its highly recommended to fix the deployment for showcasing your projects later.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-01 18:12 UTC, merged

2022-12-11 13:41 UTC, Bantealem commented
Thank you for your inspiration and your constructive feedback.